import static org.jreleaser.model.Active.ALWAYS

plugins {
    id 'java-library'
    id 'maven-publish'

    id 'org.springframework.boot' version "$springBootVersion"
    id 'io.spring.dependency-management' version "$dependencyManagementVersion"

    id 'io.github.pluxurydolo.test-plugin' version "$testPluginVersion"
    id 'io.github.pluxurydolo.logs-validation-plugin' version "$logsValidationPluginVersion"
    id 'io.github.pluxurydolo.checkstyle-plugin' version "$checkstylePluginVersion"
    id 'io.github.pluxurydolo.version-plugin' version "$versionPluginVersion"

    id 'org.jreleaser' version "$jreleaserVersion"
}

group = 'io.github.pluxurydolo'

java {
    withJavadocJar()
    withSourcesJar()
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

bootJar {
    enabled = false
}

repositories {
    mavenCentral()
}

afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
                from components.java

                pom {
                    name = 'youtube-spring-boot-starter'
                    description = 'YouTube Spring Boot Starter made for personal use'
                    url = 'https://github.com/pluxurydolo/youtube-spring-boot-starter'

                    developers {
                        developer {
                            id = 'pluxurydolo'
                            name = 'Alexander'
                        }
                    }

                    scm {
                        url = 'scm:git:git://github.com/youtube-spring-boot-starter.git'
                        connection = 'scm:git:git://github.com/youtube-spring-boot-starter.git'
                        tag = project.version
                    }

                    licenses {
                        license {
                            name = 'The Apache License, Version 2.0'
                            url = 'http://www.apache.org/licenses/LICENSE-2.0.txt'
                        }
                    }
                }
            }
        }

        repositories {
            maven {
                url = uri layout.buildDirectory.dir('staging-deploy')
            }
        }
    }
}

jreleaser {
    release {
        github {
            skipRelease.set true
            skipTag.set true
        }
    }

    signing {
        active.set ALWAYS
        armored.set true
        verify.set true
    }

    project {
        inceptionYear.set '2026'
        author('@pluxurydolo')
    }

    deploy {
        maven {
            mavenCentral.create('sonatype') {
                active.set ALWAYS
                url = 'https://central.sonatype.com/api/v1/publisher'
                stagingRepository layout.buildDirectory.dir('staging-deploy').get().toString()
                setAuthorization 'Basic'
                retryDelay.set 60
            }
        }
    }
}

dependencies {
    implementation "org.springframework.boot:spring-boot-starter:$springBootVersion"
    implementation "org.springframework.boot:spring-boot-starter-webflux:$springBootVersion"

    implementation "com.google.api-client:google-api-client:$googleApiClientVersion"
    implementation "com.google.apis:google-api-services-youtube:$youtubeApiVersion"

    testImplementation "org.springframework.boot:spring-boot-starter-webflux-test:$springBootVersion"
}
