spring:
  main:
    allow-bean-definition-overriding: true
youtube:
  auth:
    application-name: app-name
    redirect-uri: http://localhost:8888$/app-name/v1/youtube/login/redirect
  endpoint:
    login: /app-name/v1/youtube/login
    redirect: /app-name/v1/youtube/login/redirect
    refresh-token: /app-name/v1/youtube/refresh-token
  scheduler:
    refresh-token:
      cron: 0 0 0 * * SUN
      zone: Europe/Moscow
